### ISSUE TITLE
Should we keep the old license?

### ISSUE THREAD

**Issue by iamthemuffinman** [ericlagergren/go-coreutils#99]
Should we keep the license on the files merged from gonix or change it to what go-coreutils uses? Brought up here: https://github.com/EricLagerg/go-coreutils/pull/98

**Comment by EricLagerg** [comment]
I'll email Polegone and see what he thinks. Until then, we should keep
the licenses. It wasn't all his work, and his contributors contributed
the work under certain licenses. Now, if you rewrite the work to where
it's indistinguishable from the original, then you can, I believe,
change the license. For instance, I think your base64 rewrite might
qualify.
--
Eric Lagergren
ericlagergren.com

**Comment by iamthemuffinman** [comment]
I think that's fair. Any maintenance done should stay under the original license. What if for the most part the work was completely rewritten, but a small amount of the old code is still used? Does that justify a new license?

**Comment by EricLagerg** [comment]
I think so. I'm not a lawyer, but a rewrite should be fine. I added a line in CONTRIBUTING.md about author names -- basically, even if it's a rewrite, add your name under theirs. As for copyright (e.g., (c) John Doe, 2015), I think we should open an issue for each copyright change.
